const byId=id=>document.getElementById(id);
const state={url:"",article:null,translations:[],view:"ko",translating:false};
const allowedProtocols=new Set(["http:","https:"]);
const cachePrefix="juyeon-reader:";
const setNotice=(message,error=false)=>{byId("readerNotice").textContent=message;byId("readerNotice").classList.toggle("error",error)};
const setProgress=value=>{byId("readerProgress").style.width=`${Math.max(0,Math.min(100,value))}%`};
function normalizeUrl(value){try{const url=new URL(value);return allowedProtocols.has(url.protocol)?url.href:""}catch{return""}}
function cacheKey(url){let hash=2166136261;for(const char of url){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return`${cachePrefix}${(hash>>>0).toString(16)}`}
function loadCache(url){try{const value=JSON.parse(localStorage.getItem(cacheKey(url))||"null");return value?.url===url?value:null}catch{return null}}
function saveCache(){if(!state.article||!state.translations.length)return;try{localStorage.setItem(cacheKey(state.url),JSON.stringify({url:state.url,article:state.article,translations:state.translations,savedAt:Date.now()}))}catch{setNotice("번역은 완료했지만 브라우저 저장 공간이 부족해 캐시하지 못했습니다.")}}
function createText(tag,className,text){const el=document.createElement(tag);el.className=className;el.textContent=text;return el}
function render(){const root=byId("readerContent");root.replaceChildren();root.dataset.view=state.view;root.setAttribute("aria-busy",String(state.translating));if(!state.article){root.append(createText("p","reader-empty","확장이 원문을 가져오면 여기에 표시됩니다."));return}state.article.blocks.forEach((block,index)=>{const wrap=document.createElement("section");wrap.className="reader-block";const tag=/^h[1-3]$/.test(block.type)?block.type:block.type==="li"?"p":block.type==="blockquote"?"blockquote":"p";wrap.append(createText(tag,"reader-ko",state.translations[index]||"번역 대기 중…"));wrap.append(createText(tag,"reader-original",block.text));root.append(wrap)});if(!state.article.blocks.length)root.append(createText("p","reader-empty","읽을 수 있는 본문을 찾지 못했습니다. 원문 페이지에서 확장 아이콘을 눌러 다시 시도해 보세요."))}
function applyArticle(article){if(!article||!Array.isArray(article.blocks))return fail("원문에서 읽을 수 있는 내용을 찾지 못했습니다.");state.article=article;byId("readerTitle").textContent=article.title||"제목 없는 페이지";byId("readerMeta").textContent=[article.byline,article.siteName,article.lang&&`원문 ${article.lang}`,`${article.blocks.length}개 문단`].filter(Boolean).join(" · ");const cached=loadCache(state.url);if(cached?.translations?.length===article.blocks.length){state.translations=cached.translations;setProgress(100);setNotice("이전에 번역한 내용을 불러왔습니다.");}else{state.translations=[];setProgress(0);setNotice("원문을 가져왔습니다. ‘한국어 번역 시작’을 눌러주세요.");}byId("translateButton").disabled=!article.blocks.length;byId("retryButton").hidden=true;render()}
function fail(message){setNotice(message,true);byId("retryButton").hidden=false;byId("readerContent").setAttribute("aria-busy","false")}
function requestArticle(){if(!state.url)return fail("올바른 http 또는 https 주소를 입력해주세요.");state.article=null;state.translations=[];render();setProgress(5);setNotice("개인 확장에 원문을 요청하고 있습니다…");window.postMessage({source:"juyeon-reader-page",type:"JUYEON_READER_REQUEST",url:state.url},location.origin);setTimeout(()=>{if(!state.article)fail("주연뉴스 리더 확장이 응답하지 않습니다. 확장을 설치·활성화한 뒤 다시 시도해주세요.")},15000)}
async function detectLanguage(text,hint){const clean=(hint||"").toLowerCase().split("-")[0];if(clean&&clean!=="und")return clean;if("LanguageDetector"in self){const availability=await LanguageDetector.availability();if(availability!=="unavailable"){const detector=await LanguageDetector.create();const results=await detector.detect(text.slice(0,4000));detector.destroy?.();if(results[0]?.detectedLanguage)return results[0].detectedLanguage.split("-")[0]}}return"en"}
async function translate(){if(state.translating||!state.article)return;if(!("Translator"in self))return fail("이 브라우저는 기기 내 번역을 지원하지 않습니다. 데스크톱 Chrome 138 이상에서 열어주세요.");state.translating=true;byId("translateButton").disabled=true;render();try{const sample=state.article.blocks.slice(0,8).map(item=>item.text).join("\n");const sourceLanguage=await detectLanguage(sample,state.article.lang);if(sourceLanguage==="ko"){state.translations=state.article.blocks.map(item=>item.text);setProgress(100);setNotice("이미 한국어로 된 페이지입니다.");saveCache();return}const availability=await Translator.availability({sourceLanguage,targetLanguage:"ko"});if(availability==="unavailable")throw new Error(`${sourceLanguage} → 한국어 언어팩을 지원하지 않습니다.`);setNotice(availability==="downloadable"?"번역 언어팩을 내려받는 중입니다…":"문단별로 한국어 번역을 시작합니다.");const translator=await Translator.create({sourceLanguage,targetLanguage:"ko",monitor(m){m.addEventListener("downloadprogress",event=>{setProgress(Math.round(event.loaded*15));setNotice(`번역 언어팩 다운로드 ${Math.round(event.loaded*100)}%`)})}});state.translations=new Array(state.article.blocks.length).fill("");for(let i=0;i<state.article.blocks.length;i++){state.translations[i]=await translator.translate(state.article.blocks[i].text);setProgress(15+Math.round(((i+1)/state.article.blocks.length)*85));setNotice(`한국어 번역 중 ${i+1}/${state.article.blocks.length}`);if(i%4===0)render()}translator.destroy?.();saveCache();setNotice("한국어 전문 번역을 완료했습니다.");}catch(error){fail(error.message||"번역 중 오류가 발생했습니다.")}finally{state.translating=false;byId("translateButton").disabled=false;render()}}
window.addEventListener("message",event=>{if(event.source!==window||event.data?.source!=="juyeon-reader-extension")return;if(event.data.type==="JUYEON_READER_RESULT")applyArticle(event.data.article);if(event.data.type==="JUYEON_READER_ERROR")fail(event.data.message||"원문을 가져오지 못했습니다.")});
document.querySelectorAll("[data-reader-view]").forEach(button=>button.addEventListener("click",()=>{state.view=button.dataset.readerView;document.querySelectorAll("[data-reader-view]").forEach(item=>{const active=item===button;item.classList.toggle("active",active);item.setAttribute("aria-pressed",String(active))});render()}));
byId("translateButton").addEventListener("click",translate);byId("retryButton").addEventListener("click",requestArticle);byId("backButton").addEventListener("click",()=>history.length>1?history.back():location.assign("./"));byId("loadUrlButton").addEventListener("click",()=>{const url=normalizeUrl(byId("readerUrl").value);if(!url)return fail("올바른 웹주소를 입력해주세요.");location.search=`?url=${encodeURIComponent(url)}`});byId("readerUrl").addEventListener("keydown",event=>{if(event.key==="Enter")byId("loadUrlButton").click()});byId("clearCacheButton").addEventListener("click",()=>{if(state.url)localStorage.removeItem(cacheKey(state.url));state.translations=[];setProgress(0);setNotice("이 글의 저장된 번역을 삭제했습니다.");render()});
state.url=normalizeUrl(new URLSearchParams(location.search).get("url")||"");byId("readerUrl").value=state.url;byId("originalTop").href=state.url||"#";if(state.url)requestArticle();else{setNotice("번역할 외국어 페이지 주소를 입력해주세요.");byId("readerTitle").textContent="외국어 페이지 한국어 읽기모드"}
